services:
  app:
    # image: docker.aoirint.com/aoirint/live_inbox_updater:latest
    build: .
    restart: always
    environment:
      - LIVE_INBOX_HASURA_URL=${LIVE_INBOX_HASURA_URL:?}
      - LIVE_INBOX_HASURA_TOKEN=${LIVE_INBOX_HASURA_TOKEN:?}
      - APP_STORAGE_TYPE=${APP_STORAGE_TYPE:?}
      - APP_STORAGE_FILE_DIR
      - APP_STORAGE_S3_BUCKET_NAME
      - APP_STORAGE_S3_ENDPOINT_URL
      - APP_STORAGE_S3_REGION_NAME
      - APP_STORAGE_S3_ACCESS_KEY_ID
      - APP_STORAGE_S3_SECRET_ACCESS_KEY
      - APP_USERAGENT=${APP_USERAGENT:?}
      - APP_UPDATE_INTERVAL=${APP_UPDATE_INTERVAL:?}
    volumes:
      - "./cache/niconico_user_icons:/code/live_inbox_updater/cache/niconico_user_icons"
