services:
  app:
    # image: docker.aoirint.com/aoirint/live_inbox_updater:latest
    build: .
    restart: always
    environment:
      - LIVE_INBOX_HASURA_URL=${LIVE_INBOX_HASURA_URL:?}
      - LIVE_INBOX_HASURA_TOKEN=${LIVE_INBOX_HASURA_TOKEN:?}
      - APP_NICONICO_USER_ICON_DIR=${APP_NICONICO_USER_ICON_DIR:?}
      - APP_USERAGENT=${APP_USERAGENT:?}
      - APP_UPDATE_INTERVAL=${APP_UPDATE_INTERVAL:?}
    volumes:
      - "./cache/niconico_user_icons:/code/live_inbox_updater/cache/niconico_user_icons"
